RFC2986 = {'PKCS-10': {'extensibility-implied': False,
             'imports': {'AuthenticationFramework': ['ALGORITHM'],
                         'InformationFramework': ['ATTRIBUTE', 'Name'],
                         'UsefulDefinitions': ['informationFramework',
                                               'authenticationFramework']},
             'object-classes': {},
             'object-sets': {'CRIAttributes': {'class': 'ATTRIBUTE',
                                               'members': ['.']},
                             'PKInfoAlgorithms': {'class': 'ALGORITHM',
                                                  'members': ['.']},
                             'SignatureAlgorithms': {'class': 'ALGORITHM',
                                                     'members': ['.']}},
             'tags': 'IMPLICIT',
             'types': {'AlgorithmIdentifier': {'members': [{'name': 'algorithm',
                                                            'optional': False,
                                                            'table': 'IOSet',
                                                            'type': 'ALGORITHM.&id'},
                                                           {'name': 'parameters',
                                                            'optional': True,
                                                            'table': ['IOSet',
                                                                      ['algorithm']],
                                                            'type': 'ALGORITHM.&Type'}],
                                               'type': 'SEQUENCE'},
                       'Attribute': {'members': [{'name': 'type',
                                                  'optional': False,
                                                  'table': 'IOSet',
                                                  'type': 'ATTRIBUTE.&id'},
                                                 {'element': {'table': ['IOSet',
                                                                        ['type']],
                                                              'type': 'ATTRIBUTE.&Type'},
                                                  'name': 'values',
                                                  'optional': False,
                                                  'size': [(1, 'MAX')],
                                                  'type': 'SET OF'}],
                                     'type': 'SEQUENCE'},
                       'Attributes': {'element': {'type': 'Attribute'},
                                      'size': None,
                                      'type': 'SET OF'},
                       'CertificationRequest': {'members': [{'name': 'certificationRequestInfo',
                                                             'optional': False,
                                                             'type': 'CertificationRequestInfo'},
                                                            {'name': 'signatureAlgorithm',
                                                             'optional': False,
                                                             'type': 'AlgorithmIdentifier'},
                                                            {'name': 'signature',
                                                             'optional': False,
                                                             'size': None,
                                                             'type': 'BIT '
                                                                     'STRING'}],
                                                'type': 'SEQUENCE'},
                       'CertificationRequestInfo': {'members': [{'name': 'version',
                                                                 'optional': False,
                                                                 'restricted-to': ['v1'],
                                                                 'type': 'INTEGER'},
                                                                {'name': 'subject',
                                                                 'optional': False,
                                                                 'type': 'Name'},
                                                                {'name': 'subjectPKInfo',
                                                                 'optional': False,
                                                                 'type': 'SubjectPublicKeyInfo'},
                                                                {'name': 'attributes',
                                                                 'optional': False,
                                                                 'tag': {'number': 0},
                                                                 'type': 'Attributes'}],
                                                    'type': 'SEQUENCE'},
                       'SubjectPublicKeyInfo': {'members': [{'name': 'algorithm',
                                                             'optional': False,
                                                             'type': 'AlgorithmIdentifier'},
                                                            {'name': 'subjectPublicKey',
                                                             'optional': False,
                                                             'size': None,
                                                             'type': 'BIT '
                                                                     'STRING'}],
                                                'type': 'SEQUENCE'}},
             'values': {}}}
