EXPECTED = {'Lightweight-Directory-Access-Protocol-V3': {'extensibility-implied': True,
                                              'imports': {},
                                              'object-classes': {},
                                              'object-sets': {},
                                              'tags': 'IMPLICIT',
                                              'types': {'AbandonRequest': {'tag': {'class': 'APPLICATION',
                                                                                   'number': 16},
                                                                           'type': 'MessageID'},
                                                        'AddRequest': {'members': [{'name': 'entry',
                                                                                    'type': 'LDAPDN'},
                                                                                   {'name': 'attributes',
                                                                                    'type': 'AttributeList'}],
                                                                       'tag': {'class': 'APPLICATION',
                                                                               'number': 8},
                                                                       'type': 'SEQUENCE'},
                                                        'AddResponse': {'tag': {'class': 'APPLICATION',
                                                                                'number': 9},
                                                                        'type': 'LDAPResult'},
                                                        'AssertionValue': {'type': 'OCTET '
                                                                                   'STRING'},
                                                        'Attribute': {'type': 'PartialAttribute'},
                                                        'AttributeDescription': {'type': 'LDAPString'},
                                                        'AttributeList': {'element': {'type': 'Attribute'},
                                                                          'type': 'SEQUENCE '
                                                                                  'OF'},
                                                        'AttributeSelection': {'element': {'type': 'LDAPString'},
                                                                               'type': 'SEQUENCE '
                                                                                       'OF'},
                                                        'AttributeValue': {'type': 'OCTET '
                                                                                   'STRING'},
                                                        'AttributeValueAssertion': {'members': [{'name': 'attributeDesc',
                                                                                                 'type': 'AttributeDescription'},
                                                                                                {'name': 'assertionValue',
                                                                                                 'type': 'AssertionValue'}],
                                                                                    'type': 'SEQUENCE'},
                                                        'AuthenticationChoice': {'members': [{'name': 'simple',
                                                                                              'tag': {'number': 0},
                                                                                              'type': 'OCTET '
                                                                                                      'STRING'},
                                                                                             {'name': 'sasl',
                                                                                              'tag': {'number': 3},
                                                                                              'type': 'SaslCredentials'},
                                                                                             '...'],
                                                                                 'type': 'CHOICE'},
                                                        'BindRequest': {'members': [{'name': 'version',
                                                                                     'restricted-to': [(1,
                                                                                                        127)],
                                                                                     'type': 'INTEGER'},
                                                                                    {'name': 'name',
                                                                                     'type': 'LDAPDN'},
                                                                                    {'name': 'authentication',
                                                                                     'type': 'AuthenticationChoice'}],
                                                                        'tag': {'class': 'APPLICATION',
                                                                                'number': 0},
                                                                        'type': 'SEQUENCE'},
                                                        'BindResponse': {'members': [{'components-of': 'LDAPResult'},
                                                                                     {'name': 'serverSaslCreds',
                                                                                      'optional': True,
                                                                                      'tag': {'number': 7},
                                                                                      'type': 'OCTET '
                                                                                              'STRING'}],
                                                                         'tag': {'class': 'APPLICATION',
                                                                                 'number': 1},
                                                                         'type': 'SEQUENCE'},
                                                        'CompareRequest': {'members': [{'name': 'entry',
                                                                                        'type': 'LDAPDN'},
                                                                                       {'name': 'ava',
                                                                                        'type': 'AttributeValueAssertion'}],
                                                                           'tag': {'class': 'APPLICATION',
                                                                                   'number': 14},
                                                                           'type': 'SEQUENCE'},
                                                        'CompareResponse': {'tag': {'class': 'APPLICATION',
                                                                                    'number': 15},
                                                                            'type': 'LDAPResult'},
                                                        'Control': {'members': [{'name': 'controlType',
                                                                                 'type': 'LDAPOID'},
                                                                                {'default': 'FALSE',
                                                                                 'name': 'criticality',
                                                                                 'type': 'BOOLEAN'},
                                                                                {'name': 'controlValue',
                                                                                 'optional': True,
                                                                                 'type': 'OCTET '
                                                                                         'STRING'}],
                                                                    'type': 'SEQUENCE'},
                                                        'Controls': {'element': {'type': 'Control'},
                                                                     'type': 'SEQUENCE '
                                                                             'OF'},
                                                        'DelRequest': {'tag': {'class': 'APPLICATION',
                                                                               'number': 10},
                                                                       'type': 'LDAPDN'},
                                                        'DelResponse': {'tag': {'class': 'APPLICATION',
                                                                                'number': 11},
                                                                        'type': 'LDAPResult'},
                                                        'ExtendedRequest': {'members': [{'name': 'requestName',
                                                                                         'tag': {'number': 0},
                                                                                         'type': 'LDAPOID'},
                                                                                        {'name': 'requestValue',
                                                                                         'optional': True,
                                                                                         'tag': {'number': 1},
                                                                                         'type': 'OCTET '
                                                                                                 'STRING'}],
                                                                            'tag': {'class': 'APPLICATION',
                                                                                    'number': 23},
                                                                            'type': 'SEQUENCE'},
                                                        'ExtendedResponse': {'members': [{'components-of': 'LDAPResult'},
                                                                                         {'name': 'responseName',
                                                                                          'optional': True,
                                                                                          'tag': {'number': 10},
                                                                                          'type': 'LDAPOID'},
                                                                                         {'name': 'responseValue',
                                                                                          'optional': True,
                                                                                          'tag': {'number': 11},
                                                                                          'type': 'OCTET '
                                                                                                  'STRING'}],
                                                                             'tag': {'class': 'APPLICATION',
                                                                                     'number': 24},
                                                                             'type': 'SEQUENCE'},
                                                        'Filter': {'members': [{'element': {'type': 'Filter'},
                                                                                'name': 'and',
                                                                                'size': [(1,
                                                                                          'MAX')],
                                                                                'tag': {'number': 0},
                                                                                'type': 'SET '
                                                                                        'OF'},
                                                                               {'element': {'type': 'Filter'},
                                                                                'name': 'or',
                                                                                'size': [(1,
                                                                                          'MAX')],
                                                                                'tag': {'number': 1},
                                                                                'type': 'SET '
                                                                                        'OF'},
                                                                               {'name': 'not',
                                                                                'tag': {'number': 2},
                                                                                'type': 'Filter'},
                                                                               {'name': 'equalityMatch',
                                                                                'tag': {'number': 3},
                                                                                'type': 'AttributeValueAssertion'},
                                                                               {'name': 'substrings',
                                                                                'tag': {'number': 4},
                                                                                'type': 'SubstringFilter'},
                                                                               {'name': 'greaterOrEqual',
                                                                                'tag': {'number': 5},
                                                                                'type': 'AttributeValueAssertion'},
                                                                               {'name': 'lessOrEqual',
                                                                                'tag': {'number': 6},
                                                                                'type': 'AttributeValueAssertion'},
                                                                               {'name': 'present',
                                                                                'tag': {'number': 7},
                                                                                'type': 'AttributeDescription'},
                                                                               {'name': 'approxMatch',
                                                                                'tag': {'number': 8},
                                                                                'type': 'AttributeValueAssertion'},
                                                                               {'name': 'extensibleMatch',
                                                                                'tag': {'number': 9},
                                                                                'type': 'MatchingRuleAssertion'},
                                                                               '...'],
                                                                   'type': 'CHOICE'},
                                                        'IntermediateResponse': {'members': [{'name': 'responseName',
                                                                                              'optional': True,
                                                                                              'tag': {'number': 0},
                                                                                              'type': 'LDAPOID'},
                                                                                             {'name': 'responseValue',
                                                                                              'optional': True,
                                                                                              'tag': {'number': 1},
                                                                                              'type': 'OCTET '
                                                                                                      'STRING'}],
                                                                                 'tag': {'class': 'APPLICATION',
                                                                                         'number': 25},
                                                                                 'type': 'SEQUENCE'},
                                                        'LDAPDN': {'type': 'LDAPString'},
                                                        'LDAPMessage': {'members': [{'name': 'messageID',
                                                                                     'type': 'MessageID'},
                                                                                    {'members': [{'name': 'bindRequest',
                                                                                                  'type': 'BindRequest'},
                                                                                                 {'name': 'bindResponse',
                                                                                                  'type': 'BindResponse'},
                                                                                                 {'name': 'unbindRequest',
                                                                                                  'type': 'UnbindRequest'},
                                                                                                 {'name': 'searchRequest',
                                                                                                  'type': 'SearchRequest'},
                                                                                                 {'name': 'searchResEntry',
                                                                                                  'type': 'SearchResultEntry'},
                                                                                                 {'name': 'searchResDone',
                                                                                                  'type': 'SearchResultDone'},
                                                                                                 {'name': 'searchResRef',
                                                                                                  'type': 'SearchResultReference'},
                                                                                                 {'name': 'modifyRequest',
                                                                                                  'type': 'ModifyRequest'},
                                                                                                 {'name': 'modifyResponse',
                                                                                                  'type': 'ModifyResponse'},
                                                                                                 {'name': 'addRequest',
                                                                                                  'type': 'AddRequest'},
                                                                                                 {'name': 'addResponse',
                                                                                                  'type': 'AddResponse'},
                                                                                                 {'name': 'delRequest',
                                                                                                  'type': 'DelRequest'},
                                                                                                 {'name': 'delResponse',
                                                                                                  'type': 'DelResponse'},
                                                                                                 {'name': 'modDNRequest',
                                                                                                  'type': 'ModifyDNRequest'},
                                                                                                 {'name': 'modDNResponse',
                                                                                                  'type': 'ModifyDNResponse'},
                                                                                                 {'name': 'compareRequest',
                                                                                                  'type': 'CompareRequest'},
                                                                                                 {'name': 'compareResponse',
                                                                                                  'type': 'CompareResponse'},
                                                                                                 {'name': 'abandonRequest',
                                                                                                  'type': 'AbandonRequest'},
                                                                                                 {'name': 'extendedReq',
                                                                                                  'type': 'ExtendedRequest'},
                                                                                                 {'name': 'extendedResp',
                                                                                                  'type': 'ExtendedResponse'},
                                                                                                 '...',
                                                                                                 {'name': 'intermediateResponse',
                                                                                                  'type': 'IntermediateResponse'}],
                                                                                     'name': 'protocolOp',
                                                                                     'type': 'CHOICE'},
                                                                                    {'name': 'controls',
                                                                                     'optional': True,
                                                                                     'tag': {'number': 0},
                                                                                     'type': 'Controls'}],
                                                                        'type': 'SEQUENCE'},
                                                        'LDAPOID': {'type': 'OCTET '
                                                                            'STRING'},
                                                        'LDAPResult': {'members': [{'name': 'resultCode',
                                                                                    'type': 'ENUMERATED',
                                                                                    'values': {0: 'success',
                                                                                               1: 'operationsError',
                                                                                               2: 'protocolError',
                                                                                               3: 'timeLimitExceeded',
                                                                                               4: 'sizeLimitExceeded',
                                                                                               5: 'compareFalse',
                                                                                               6: 'compareTrue',
                                                                                               7: 'authMethodNotSupported',
                                                                                               8: 'strongerAuthRequired',
                                                                                               10: 'referral',
                                                                                               11: 'adminLimitExceeded',
                                                                                               12: 'unavailableCriticalExtension',
                                                                                               13: 'confidentialityRequired',
                                                                                               14: 'saslBindInProgress',
                                                                                               16: 'noSuchAttribute',
                                                                                               17: 'undefinedAttributeType',
                                                                                               18: 'inappropriateMatching',
                                                                                               19: 'constraintViolation',
                                                                                               20: 'attributeOrValueExists',
                                                                                               21: 'invalidAttributeSyntax',
                                                                                               32: 'noSuchObject',
                                                                                               33: 'aliasProblem',
                                                                                               34: 'invalidDNSyntax',
                                                                                               36: 'aliasDereferencingProblem',
                                                                                               48: 'inappropriateAuthentication',
                                                                                               49: 'invalidCredentials',
                                                                                               50: 'insufficientAccessRights',
                                                                                               51: 'busy',
                                                                                               52: 'unavailable',
                                                                                               53: 'unwillingToPerform',
                                                                                               54: 'loopDetect',
                                                                                               64: 'namingViolation',
                                                                                               65: 'objectClassViolation',
                                                                                               66: 'notAllowedOnNonLeaf',
                                                                                               67: 'notAllowedOnRDN',
                                                                                               68: 'entryAlreadyExists',
                                                                                               69: 'objectClassModsProhibited',
                                                                                               71: 'affectsMultipleDSAs',
                                                                                               80: 'other',
                                                                                               81: '...'}},
                                                                                   {'name': 'matchedDN',
                                                                                    'type': 'LDAPDN'},
                                                                                   {'name': 'diagnosticMessage',
                                                                                    'type': 'LDAPString'},
                                                                                   {'name': 'referral',
                                                                                    'optional': True,
                                                                                    'tag': {'number': 3},
                                                                                    'type': 'Referral'}],
                                                                       'type': 'SEQUENCE'},
                                                        'LDAPString': {'type': 'OCTET '
                                                                               'STRING'},
                                                        'MatchingRuleAssertion': {'members': [{'name': 'matchingRule',
                                                                                               'optional': True,
                                                                                               'tag': {'number': 1},
                                                                                               'type': 'MatchingRuleId'},
                                                                                              {'name': 'type',
                                                                                               'optional': True,
                                                                                               'tag': {'number': 2},
                                                                                               'type': 'AttributeDescription'},
                                                                                              {'name': 'matchValue',
                                                                                               'tag': {'number': 3},
                                                                                               'type': 'AssertionValue'},
                                                                                              {'default': 'FALSE',
                                                                                               'name': 'dnAttributes',
                                                                                               'tag': {'number': 4},
                                                                                               'type': 'BOOLEAN'}],
                                                                                  'type': 'SEQUENCE'},
                                                        'MatchingRuleId': {'type': 'LDAPString'},
                                                        'MessageID': {'restricted-to': [(0,
                                                                                         'maxInt')],
                                                                      'type': 'INTEGER'},
                                                        'ModifyDNRequest': {'members': [{'name': 'entry',
                                                                                         'type': 'LDAPDN'},
                                                                                        {'name': 'newrdn',
                                                                                         'type': 'RelativeLDAPDN'},
                                                                                        {'name': 'deleteoldrdn',
                                                                                         'type': 'BOOLEAN'},
                                                                                        {'name': 'newSuperior',
                                                                                         'optional': True,
                                                                                         'tag': {'number': 0},
                                                                                         'type': 'LDAPDN'}],
                                                                            'tag': {'class': 'APPLICATION',
                                                                                    'number': 12},
                                                                            'type': 'SEQUENCE'},
                                                        'ModifyDNResponse': {'tag': {'class': 'APPLICATION',
                                                                                     'number': 13},
                                                                             'type': 'LDAPResult'},
                                                        'ModifyRequest': {'members': [{'name': 'object',
                                                                                       'type': 'LDAPDN'},
                                                                                      {'element': {'members': [{'name': 'operation',
                                                                                                                'type': 'ENUMERATED',
                                                                                                                'values': {0: 'add',
                                                                                                                           1: 'delete',
                                                                                                                           2: 'replace',
                                                                                                                           3: '...'}},
                                                                                                               {'name': 'modification',
                                                                                                                'type': 'PartialAttribute'}],
                                                                                                   'type': 'SEQUENCE'},
                                                                                       'name': 'changes',
                                                                                       'type': 'SEQUENCE '
                                                                                               'OF'}],
                                                                          'tag': {'class': 'APPLICATION',
                                                                                  'number': 6},
                                                                          'type': 'SEQUENCE'},
                                                        'ModifyResponse': {'tag': {'class': 'APPLICATION',
                                                                                   'number': 7},
                                                                           'type': 'LDAPResult'},
                                                        'PartialAttribute': {'members': [{'name': 'type',
                                                                                          'type': 'AttributeDescription'},
                                                                                         {'element': {'type': 'AttributeValue'},
                                                                                          'name': 'vals',
                                                                                          'type': 'SET '
                                                                                                  'OF'}],
                                                                             'type': 'SEQUENCE'},
                                                        'PartialAttributeList': {'element': {'type': 'PartialAttribute'},
                                                                                 'type': 'SEQUENCE '
                                                                                         'OF'},
                                                        'Referral': {'element': {'type': 'URI'},
                                                                     'size': [(1,
                                                                               'MAX')],
                                                                     'type': 'SEQUENCE '
                                                                             'OF'},
                                                        'RelativeLDAPDN': {'type': 'LDAPString'},
                                                        'SaslCredentials': {'members': [{'name': 'mechanism',
                                                                                         'type': 'LDAPString'},
                                                                                        {'name': 'credentials',
                                                                                         'optional': True,
                                                                                         'type': 'OCTET '
                                                                                                 'STRING'}],
                                                                            'type': 'SEQUENCE'},
                                                        'SearchRequest': {'members': [{'name': 'baseObject',
                                                                                       'type': 'LDAPDN'},
                                                                                      {'name': 'scope',
                                                                                       'type': 'ENUMERATED',
                                                                                       'values': {0: 'baseObject',
                                                                                                  1: 'singleLevel',
                                                                                                  2: 'wholeSubtree',
                                                                                                  3: '...'}},
                                                                                      {'name': 'derefAliases',
                                                                                       'type': 'ENUMERATED',
                                                                                       'values': {0: 'neverDerefAliases',
                                                                                                  1: 'derefInSearching',
                                                                                                  2: 'derefFindingBaseObj',
                                                                                                  3: 'derefAlways'}},
                                                                                      {'name': 'sizeLimit',
                                                                                       'restricted-to': [(0,
                                                                                                          'maxInt')],
                                                                                       'type': 'INTEGER'},
                                                                                      {'name': 'timeLimit',
                                                                                       'restricted-to': [(0,
                                                                                                          'maxInt')],
                                                                                       'type': 'INTEGER'},
                                                                                      {'name': 'typesOnly',
                                                                                       'type': 'BOOLEAN'},
                                                                                      {'name': 'filter',
                                                                                       'type': 'Filter'},
                                                                                      {'name': 'attributes',
                                                                                       'type': 'AttributeSelection'}],
                                                                          'tag': {'class': 'APPLICATION',
                                                                                  'number': 3},
                                                                          'type': 'SEQUENCE'},
                                                        'SearchResultDone': {'tag': {'class': 'APPLICATION',
                                                                                     'number': 5},
                                                                             'type': 'LDAPResult'},
                                                        'SearchResultEntry': {'members': [{'name': 'objectName',
                                                                                           'type': 'LDAPDN'},
                                                                                          {'name': 'attributes',
                                                                                           'type': 'PartialAttributeList'}],
                                                                              'tag': {'class': 'APPLICATION',
                                                                                      'number': 4},
                                                                              'type': 'SEQUENCE'},
                                                        'SearchResultReference': {'element': {'type': 'URI'},
                                                                                  'size': [(1,
                                                                                            'MAX')],
                                                                                  'tag': {'class': 'APPLICATION',
                                                                                          'number': 19},
                                                                                  'type': 'SEQUENCE '
                                                                                          'OF'},
                                                        'SubstringFilter': {'members': [{'name': 'type',
                                                                                         'type': 'AttributeDescription'},
                                                                                        {'element': {'members': [{'name': 'initial',
                                                                                                                  'tag': {'number': 0},
                                                                                                                  'type': 'AssertionValue'},
                                                                                                                 {'name': 'any',
                                                                                                                  'tag': {'number': 1},
                                                                                                                  'type': 'AssertionValue'},
                                                                                                                 {'name': 'final',
                                                                                                                  'tag': {'number': 2},
                                                                                                                  'type': 'AssertionValue'}],
                                                                                                     'type': 'CHOICE'},
                                                                                         'name': 'substrings',
                                                                                         'size': [(1,
                                                                                                   'MAX')],
                                                                                         'type': 'SEQUENCE '
                                                                                                 'OF'}],
                                                                            'type': 'SEQUENCE'},
                                                        'URI': {'type': 'LDAPString'},
                                                        'UnbindRequest': {'tag': {'class': 'APPLICATION',
                                                                                  'number': 2},
                                                                          'type': 'NULL'}},
                                              'values': {'maxInt': {'type': 'INTEGER',
                                                                    'value': 2147483647}}}}
