EXPECTED = {'AllTypes': {'extensibility-implied': False,
              'imports': {},
              'object-classes': {},
              'object-sets': {},
              'tags': 'AUTOMATIC',
              'types': {'Sequence13': {'members': [{'components-of': 'Sequence9'},
                                                   {'name': 'c',
                                                    'type': 'INTEGER'}],
                                       'type': 'SEQUENCE'},
                        'Sequence14': {'members': [{'components-of': 'Sequence13'},
                                                   {'name': 'd',
                                                    'type': 'BOOLEAN'}],
                                       'type': 'SEQUENCE'},
                        'Sequence9': {'members': [{'name': 'a',
                                                   'type': 'INTEGER'},
                                                  {'name': 'b',
                                                   'optional': True,
                                                   'type': 'BOOLEAN'}],
                                      'type': 'SEQUENCE'}},
              'values': {}}}