AllTypes DEFINITIONS ::= BEGIN

Boolean ::= BOOLEAN

Integer ::= INTEGER

Bitstring ::= BIT STRING

Bitstring2 ::= BIT STRING (SIZE(9))

Bitstring3 ::= BIT STRING (SIZE(5..7))

Octetstring ::= OCTET STRING

Octetstring2 ::= OCTET STRING (SIZE(2))

Octetstring3 ::= OCTET STRING (SIZE(3))

Octetstring4 ::= OCTET STRING (SIZE(3..7))

Null ::= NULL

Objectidentifier ::= OBJECT IDENTIFIER

Enumerated ::= ENUMERATED { one(1) }

Utf8string ::= UTF8String

Sequence ::= SEQUENCE {}

Set ::= SET {}

Sequence2 ::= SEQUENCE {
  a INTEGER DEFAULT 0
}

Set2 ::= SET {
  a INTEGER DEFAULT 1
}

Numericstring ::= NumericString

Printablestring ::= PrintableString

Ia5string ::= IA5String

Universalstring ::= UniversalString

Visiblestring ::= VisibleString

Bmpstring ::= BMPString

Teletexstring ::= TeletexString

Utctime ::= UTCTime

SequenceOf ::= SEQUENCE OF INTEGER

SetOf ::= SET OF INTEGER

END
