EXPECTED = {'Bar': {'extensibility-implied': False,
         'imports': {},
         'object-classes': {},
         'object-sets': {},
         'tags': 'EXPLICIT',
         'types': {'AcceptTypes': {'members': [{'element': {'size': None,
                                                            'type': 'BIT '
                                                                    'STRING'},
                                                'name': 'standardTypes',
                                                'optional': True,
                                                'size': None,
                                                'tag': {'kind': 'IMPLICIT',
                                                        'number': 0},
                                                'type': 'SEQUENCE OF'},
                                               {'element': {'size': None,
                                                            'type': 'OCTET '
                                                                    'STRING'},
                                                'name': 'otherTypes',
                                                'optional': True,
                                                'size': None,
                                                'tag': {'kind': 'IMPLICIT',
                                                        'number': 1},
                                                'type': 'SEQUENCE OF'}],
                                   'tag': {'class': 'APPLICATION',
                                           'kind': 'IMPLICIT',
                                           'number': 1},
                                   'type': 'SEQUENCE'},
                   'GetRequest': {'members': [{'name': 'headerOnly',
                                               'type': 'BOOLEAN'},
                                              {'name': 'lock',
                                               'type': 'BOOLEAN'},
                                              {'name': 'acceptTypes',
                                               'optional': True,
                                               'type': 'AcceptTypes'},
                                              {'name': 'url',
                                               'size': None,
                                               'type': 'OCTET STRING'}],
                                  'tag': {'class': 'APPLICATION',
                                          'kind': 'IMPLICIT',
                                          'number': 0},
                                  'type': 'SEQUENCE'}},
         'values': {}}}