CSource DEFINITIONS AUTOMATIC TAGS ::=

BEGIN

IMPORTS

    Int8,
    Int16,
    Int32,
    Int64,
    Uint8,
    Uint16,
    Uint32,
    Uint64,
    Float,
    Double,
    Bool,
    String,
    Bytes
FROM ProgrammingTypes;

A ::= SEQUENCE {
    a    Int8,
    b    Int16,
    c    Int32,
    d    Int64,
    e    Uint8,
    f    Uint16,
    g    Uint32,
    h    Uint64,
    i    Float,
    j    Double,
    k    Bool,
    l    Bytes  (SIZE(11))
}

END
