CSource DEFINITIONS AUTOMATIC TAGS ::=

BEGIN

IMPORTS

    Int8,
    Int16,
    Int32,
    Int64,
    Uint8,
    Uint16,
    Uint32,
    Uint64,
    Float,
    Double,
    Bool,
    String,
    Bytes
FROM ProgrammingTypes;

A ::= SEQUENCE {
    a    Int8,
    b    Int16,
    c    Int32,
    d    Int64,
    e    Uint8,
    f    Uint16,
    g    Uint32,
    h    Uint64,
    i    Float,
    j    Double,
    k    Bool,
    l    Bytes  (SIZE(11))
}

B ::= CHOICE {
    a    Int8,
    b    A,
    c    NULL
}

C ::= SEQUENCE (SIZE(0..2)) OF B

D ::= SEQUENCE (SIZE(1..10)) OF SEQUENCE {
    a SEQUENCE {
        b CHOICE {
            c INTEGER (0..1),
            d BOOLEAN
        },
        e SEQUENCE (SIZE(3..4)) OF NULL,
        f NULL
    },
    g SEQUENCE {
        h ENUMERATED {
            i, j, k
        },
        l OCTET STRING (SIZE(1..2))
    },
    m SEQUENCE {
        n BOOLEAN OPTIONAL,
        o INTEGER (-3..3) DEFAULT 3,
        p SEQUENCE {
            q OCTET STRING (SIZE(5)),
            r BOOLEAN OPTIONAL
        } OPTIONAL
    }
}

E ::= SEQUENCE {
    a CHOICE {
        b CHOICE {
            c BOOLEAN
        }
    }
}

F ::= SEQUENCE (SIZE (1..2)) OF SEQUENCE (SIZE (1)) OF BOOLEAN

G ::= SEQUENCE {
    a BOOLEAN OPTIONAL,
    b BOOLEAN OPTIONAL,
    c BOOLEAN OPTIONAL,
    d BOOLEAN OPTIONAL,
    e BOOLEAN OPTIONAL,
    f BOOLEAN OPTIONAL,
    g BOOLEAN OPTIONAL,
    h BOOLEAN OPTIONAL,
    i BOOLEAN OPTIONAL
}

END
