Parameterization DEFINITIONS AUTOMATIC TAGS ::=

BEGIN

A {B} ::= B

A-Boolean ::= A { BOOLEAN }

A-Integer ::= A { INTEGER }

B {A, B} ::= SEQUENCE {
    a [0] A,
    b [1] B OPTIONAL
}

B-BooleanInteger ::= B { BOOLEAN, INTEGER }
    
END
