EXPECTED = {'X683': {'extensibility-implied': False,
          'imports': {},
          'object-classes': {},
          'object-sets': {},
          'types': {'A-Boolean': {'type': 'BOOLEAN'},
                    'A-Integer': {'type': 'INTEGER'},
                    'B-BooleanInteger': {'type': 'SEQUENCE',
                                         'members': [
                                             {'type': 'BOOLEAN',
                                              'name': 'a',
                                              'tag': {'kind': 'EXPLICIT',
                                                      'number': 0},
                                              'optional': False},
                                             {'type': 'INTEGER',
                                              'name': 'b',
                                              'tag': {'kind': 'EXPLICIT',
                                                      'number': 1},
                                              'optional': True}]}},
          'values': {}}}
