EXPECTED = {'Parameterized': {'extensibility-implied': False,
                   'imports': {},
                   'object-classes': {},
                   'object-sets': {},
                   'types': {'IntegerList': {'members': [{'name': 'elem',
                                                          'type': 'INTEGER'},
                                                         {'name': 'next',
                                                          'optional': True,
                                                          'type': 'IntegerList'}],
                                             'type': 'SEQUENCE'}},
                   'values': {}}}
