EXPECTED = {'ParameterizedInformationObject': {'extensibility-implied': False,
                                    'imports': {},
                                    'object-classes': {'GC': {'members': [{'name': '&id',
                                                                           'type': 'INTEGER'},
                                                                          {'name': '&Value',
                                                                           'type': 'OpenType'}]}},
                                    'object-sets': {'GCs': {'class': 'GC',
                                                            'members': []}},
                                    'tags': 'AUTOMATIC',
                                    'types': {'D1': {'members': [{'name': 'id',
                                                                  'table': 'GCs',
                                                                  'type': 'GC.&id'},
                                                                 {'name': 'value',
                                                                  'table': ['GCs',
                                                                            ['id']],
                                                                  'type': 'GC.&Value'},
                                                                 {'name': 'a',
                                                                  'type': 'E1'}],
                                                     'type': 'SEQUENCE'},
                                              'D2': {'members': [{'name': 'id',
                                                                  'table': 'GCs',
                                                                  'type': 'GC.&id'},
                                                                 {'name': 'value',
                                                                  'table': ['GCs',
                                                                            ['id']],
                                                                  'type': 'GC.&Value'},
                                                                 {'name': 'a',
                                                                  'type': 'T1'}],
                                                     'type': 'SEQUENCE'},
                                              'E1': {'members': [{'name': 'id',
                                                                  'table': 'Param',
                                                                  'type': 'GC.&id'},
                                                                 {'name': 'value',
                                                                  'table': ['Param',
                                                                            ['id']],
                                                                  'type': 'GC.&Value'}],
                                                     'type': 'SEQUENCE'},
                                              'T1': {'members': [{'name': 'id',
                                                                  'table': 'GCs',
                                                                  'type': 'GC.&id'},
                                                                 {'name': 'value',
                                                                  'table': ['GCs',
                                                                            ['id']],
                                                                  'type': 'GC.&Value'}],
                                                     'type': 'SEQUENCE'}},
                                    'values': {}}}