EXPECTED = {'Parameterized': {'extensibility-implied': False,
                   'imports': {},
                   'object-classes': {},
                   'object-sets': {},
                   'types': {'IntegerList': {'type': 'List',
                                             'chosen-parameters': ['INTEGER']},
                             'List': {'members': [{'name': 'elem',
                                                   'type': 'ElementType'},
                                                  {'name': 'next',
                                                   'optional': True,
                                                   'type': 'List',
                                                   'parameters': ['ElementType']}],
                                      'type': 'SEQUENCE',
                                      'parameters': ['ElementType']}},
                   'values': {}}}
