SIMPLE_CLASS = {'SimpleClass': {'extensibility-implied': False,
                 'imports': {},
                 'object-classes': {'ITEM': {'members': [{'name': '&id',
                                                          'optional': False,
                                                          'type': 'INTEGER'},
                                                         {'name': '&Value',
                                                          'optional': False,
                                                          'type': 'OpenType'},
                                                         {'name': '&comment',
                                                          'optional': False,
                                                          'type': 'IA5String'}]}},
                 'object-sets': {'Items': {'class': 'ITEM',
                                           'members': [{'&Value': 'INTEGER',
                                                        '&comment': 'item 0',
                                                        '&id': 0},
                                                       {'&Value': 'BOOLEAN',
                                                        '&comment': 'item 1',
                                                        '&id': 1}]}},
                 'tags': 'AUTOMATIC',
                 'types': {'ItemWithConstraints': {'members': [{'name': 'id',
                                                                'optional': False,
                                                                'type': 'ITEM.&id'},
                                                               {'name': 'value',
                                                                'optional': False,
                                                                'type': 'ITEM.&Value'},
                                                               {'name': 'comment',
                                                                'optional': False,
                                                                'type': 'ITEM.&comment'},
                                                               {'name': 'extra',
                                                                'optional': False,
                                                                'type': 'INTEGER'}],
                                                   'type': 'SEQUENCE'},
                           'ItemWithoutConstraints': {'members': [{'name': 'id',
                                                                   'optional': False,
                                                                   'type': 'ITEM.&id'},
                                                                  {'name': 'value',
                                                                   'optional': False,
                                                                   'type': 'ITEM.&Value'},
                                                                  {'name': 'comment',
                                                                   'optional': False,
                                                                   'type': 'ITEM.&comment'},
                                                                  {'name': 'extra',
                                                                   'optional': False,
                                                                   'type': 'INTEGER'}],
                                                      'type': 'SEQUENCE'}},
                 'values': {}}}
