X680 = {'X680': {'extensibility-implied': False,
          'imports': {},
          'object-classes': {'ATTRIBUTE-E-2-15': {'members': [{'name': '&AttributeType',
                                                               'optional': False,
                                                               'type': 'OpenType'},
                                                              {'name': '&attributeId',
                                                               'optional': False,
                                                               'type': 'OBJECT IDENTIFIER'}]}},
          'object-sets': {},
          'types': {'A-19-5': {'type': 'ENUMERATED',
                               'values': {0: 'a', 1: 'c', 3: 'b', 4: '...'}},
                    'A-19-6': {'type': 'ENUMERATED',
                               'values': {0: 'a', 1: 'b', 2: '...', 3: 'c'}},
                    'ABEnvelope-E-4-a': {'type': 'Envelope'},
                    'ABEnvelope-E-4-b': {'type': 'Envelope'},
                    'ACEnvelope-E-4-a': {'type': 'Envelope'},
                    'ACEnvelope-E-4-b': {'type': 'Envelope'},
                    'AcmeBadgeNumber-E-2-12': {'tag': {'class': 'PRIVATE',
                                                       'number': 2},
                                               'type': 'INTEGER'},
                    'AngleInRadians-E-2-4': {'type': 'REAL'},
                    'App-X-Real-E-2-4': {'type': 'REAL'},
                    'AtomicNumber-E-4': {'restricted-to': [(1, 104)],
                                         'type': 'INTEGER'},
                    'Attribute-E-2-15': {'members': [{'name': 'attributeID',
                                                      'optional': False,
                                                      'table': None,
                                                      'type': 'ATTRIBUTE.&attributeId'},
                                                     {'name': 'attributeValue',
                                                      'optional': False,
                                                      'table': None,
                                                      'type': 'ATTRIBUTE.&AttributeType'}],
                                         'type': 'SEQUENCE'},
                    'B-19-6': {'type': 'ENUMERATED',
                               'values': {0: 'c', 1: '...', 2: 'd'}},
                    'BitField-E-2-5': {'size': [12], 'type': 'BIT STRING'},
                    'C-19-6': {'type': 'ENUMERATED',
                               'values': {0: 'a',
                                          1: 'b',
                                          2: '...',
                                          3: 'c',
                                          4: 'd'}},
                    'CheckingAccountBalance-E-2-2': {'type': 'INTEGER'},
                    'ChildInformation-E-1-1': {'members': [{'name': 'name',
                                                            'optional': False,
                                                            'type': 'Name-E-1-1'},
                                                           {'name': 'dateOfBirth',
                                                            'optional': False,
                                                            'type': 'Date-E-1-1'}],
                                               'type': 'SET'},
                    'Credentials-E-2-10': {'members': [{'name': 'userName',
                                                        'optional': False,
                                                        'type': 'VisibleString'},
                                                       {'name': 'password',
                                                        'optional': False,
                                                        'type': 'VisibleString'},
                                                       {'name': 'accountNumber',
                                                        'optional': False,
                                                        'type': 'INTEGER'}],
                                           'type': 'SEQUENCE'},
                    'CustomerAttribute-E-2-12-a': {'members': [{'name': 'name',
                                                                'optional': False,
                                                                'tag': {'number': 0},
                                                                'type': 'VisibleString'},
                                                               {'name': 'mailingAddress',
                                                                'optional': False,
                                                                'tag': {'number': 1},
                                                                'type': 'VisibleString'},
                                                               {'name': 'accountNumber',
                                                                'optional': False,
                                                                'tag': {'number': 2},
                                                                'type': 'INTEGER'},
                                                               {'name': 'balanceDue',
                                                                'optional': False,
                                                                'tag': {'number': 3},
                                                                'type': 'INTEGER'}],
                                                   'type': 'CHOICE'},
                    'CustomerAttribute-E-2-12-b': {'members': [{'name': 'name',
                                                                'optional': False,
                                                                'tag': {'kind': 'IMPLICIT',
                                                                        'number': 0},
                                                                'type': 'VisibleString'},
                                                               {'name': 'mailingAddress',
                                                                'optional': False,
                                                                'tag': {'kind': 'IMPLICIT',
                                                                        'number': 1},
                                                                'type': 'VisibleString'},
                                                               {'name': 'accountNumber',
                                                                'optional': False,
                                                                'tag': {'kind': 'IMPLICIT',
                                                                        'number': 2},
                                                                'type': 'INTEGER'},
                                                               {'name': 'balanceDue',
                                                                'optional': False,
                                                                'tag': {'kind': 'IMPLICIT',
                                                                        'number': 3},
                                                                'type': 'INTEGER'}],
                                                   'type': 'CHOICE'},
                    'CustomerRecord-E-2-12-a': {'members': [{'name': 'name',
                                                             'optional': False,
                                                             'tag': {'number': 0},
                                                             'type': 'VisibleString'},
                                                            {'name': 'mailingAddress',
                                                             'optional': False,
                                                             'tag': {'number': 1},
                                                             'type': 'VisibleString'},
                                                            {'name': 'accountNumber',
                                                             'optional': False,
                                                             'tag': {'number': 2},
                                                             'type': 'INTEGER'},
                                                            {'name': 'balanceDue',
                                                             'optional': False,
                                                             'tag': {'number': 3},
                                                             'type': 'INTEGER'}],
                                                'type': 'SET'},
                    'CustomerRecord-E-2-12-b': {'members': [{'name': 'name',
                                                             'optional': False,
                                                             'tag': {'kind': 'IMPLICIT',
                                                                     'number': 0},
                                                             'type': 'VisibleString'},
                                                            {'name': 'mailingAddress',
                                                             'optional': False,
                                                             'tag': {'kind': 'IMPLICIT',
                                                                     'number': 1},
                                                             'type': 'VisibleString'},
                                                            {'name': 'accountNumber',
                                                             'optional': False,
                                                             'tag': {'kind': 'IMPLICIT',
                                                                     'number': 2},
                                                             'type': 'INTEGER'},
                                                            {'name': 'balanceDue',
                                                             'optional': False,
                                                             'tag': {'kind': 'IMPLICIT',
                                                                     'number': 3},
                                                             'type': 'INTEGER'}],
                                                'type': 'SET'},
                    'D-19-5': {'type': 'ENUMERATED',
                               'values': {0: 'a', 1: 'b', 2: 'c'}},
                    'D-19-6': {'type': 'ENUMERATED',
                               'values': {0: 'a',
                                          25: 'z',
                                          26: '...',
                                          27: 'd'}},
                    'Date-E-1-1': {'tag': {'class': 'APPLICATION',
                                           'number': 3},
                                   'type': 'VisibleString'},
                    'DayOfTheMonth-E-2-2': {'type': 'INTEGER'},
                    'DayOfTheMonth-E-2-2-a': {'restricted-to': ['first',
                                                                'last'],
                                              'type': 'INTEGER'},
                    'DayOfTheMonth-E-2-2-b': {'restricted-to': [('first',
                                                                 'last')],
                                              'type': 'INTEGER'},
                    'DayOfTheWeek-E-2-3': {'type': 'ENUMERATED',
                                           'values': {0: 'sunday',
                                                      1: 'monday',
                                                      2: 'tuesday',
                                                      3: 'wednesday',
                                                      4: 'thursday',
                                                      5: 'friday',
                                                      6: 'saturday'}},
                    'DaysOfTheWeek-E-2-5': {'size': [7],
                                            'type': 'BIT STRING'},
                    'Employed-E-2-1': {'type': 'BOOLEAN'},
                    'EmployeeNumber-E-1-1': {'tag': {'class': 'APPLICATION',
                                                     'number': 2},
                                             'type': 'INTEGER'},
                    'Envelope-E-4': {'members': [{'name': 'typeA',
                                                  'optional': False,
                                                  'type': 'TypeA'},
                                                 {'name': 'typeB',
                                                  'optional': True,
                                                  'type': 'TypeB'},
                                                 {'name': 'typeC',
                                                  'optional': True,
                                                  'type': 'TypeC'}],
                                     'type': 'SET'},
                    'FileIdentifier-E-2-13-a': {'members': [{'name': 'relativeName',
                                                             'optional': False,
                                                             'type': 'VisibleString'},
                                                            {'name': 'absoluteName',
                                                             'optional': False,
                                                             'type': 'VisibleString'},
                                                            {'name': 'serialNumber',
                                                             'optional': False,
                                                             'type': 'INTEGER'}],
                                                'type': 'CHOICE'},
                    'FileIdentifier-E-2-13-b': {'members': [{'name': 'relativeName',
                                                             'optional': False,
                                                             'type': 'VisibleString'},
                                                            {'name': 'absoluteName',
                                                             'optional': False,
                                                             'type': 'VisibleString'},
                                                            {'name': '...',
                                                             'optional': False,
                                                             'type': ''},
                                                            {'name': '...',
                                                             'optional': False,
                                                             'type': ''}],
                                                'type': 'CHOICE'},
                    'FileIdentifier-E-2-13-c': {'members': [{'name': 'relativeName',
                                                             'optional': False,
                                                             'type': 'VisibleString'},
                                                            {'name': 'absoluteName',
                                                             'optional': False,
                                                             'type': 'VisibleString'},
                                                            {'name': '...',
                                                             'optional': False,
                                                             'type': ''},
                                                            {'name': 'serialNumber',
                                                             'optional': False,
                                                             'type': 'INTEGER'},
                                                            {'name': '...',
                                                             'optional': False,
                                                             'type': ''}],
                                                'type': 'CHOICE'},
                    'FileIdentifier-E-2-13-d': {'members': [{'name': 'relativeName',
                                                             'optional': False,
                                                             'type': 'VisibleString'},
                                                            {'name': 'absoluteName',
                                                             'optional': False,
                                                             'type': 'VisibleString'},
                                                            {'name': '...',
                                                             'optional': False,
                                                             'type': ''},
                                                            {'name': 'serialNumber',
                                                             'optional': False,
                                                             'type': 'INTEGER'},
                                                            {'name': 'vendorSpecific',
                                                             'optional': False,
                                                             'type': 'VendorExt'},
                                                            {'name': 'unidentified',
                                                             'optional': False,
                                                             'type': 'NULL'},
                                                            {'name': '...',
                                                             'optional': False,
                                                             'type': ''}],
                                                'type': 'CHOICE'},
                    'FileName-E-2-12': {'members': [{'name': 'directoryName',
                                                     'optional': False,
                                                     'type': 'VisibleString'},
                                                    {'name': 'directoryRelativeFileName',
                                                     'optional': False,
                                                     'type': 'VisibleString'}],
                                        'tag': {'class': 'APPLICATION',
                                                'number': 8},
                                        'type': 'SEQUENCE'},
                    'First-half-E-4': {'type': 'Months'},
                    'First-quarter-E-4': {'type': 'Months'},
                    'Fourth-quarter-E-4': {'type': 'Months'},
                    'G3FacsimilePage-E-2-5': {'size': None,
                                              'type': 'BIT STRING'},
                    'G4FacsimileImage-E-2-6': {'size': None,
                                               'type': 'OCTET STRING'},
                    'Greeting-E-2-13-a': {'members': [{'name': 'postCard',
                                                       'optional': False,
                                                       'type': 'VisibleString'},
                                                      {'name': '...',
                                                       'optional': False,
                                                       'type': ''},
                                                      {'name': '...',
                                                       'optional': False,
                                                       'type': ''}],
                                          'type': 'CHOICE'},
                    'Greeting-E-2-13-b': {'members': [{'name': 'postCard',
                                                       'optional': False,
                                                       'type': 'VisibleString'},
                                                      {'name': '...',
                                                       'optional': False,
                                                       'type': ''},
                                                      {'name': 'audio',
                                                       'optional': False,
                                                       'type': 'Audio'},
                                                      {'name': 'video',
                                                       'optional': False,
                                                       'type': 'Video'},
                                                      {'name': '...',
                                                       'optional': False,
                                                       'type': ''}],
                                          'type': 'CHOICE'},
                    'Greeting-E-2-13-c': {'members': [{'name': 'postCard',
                                                       'optional': False,
                                                       'type': 'VisibleString'},
                                                      {'name': 'recording',
                                                       'optional': False,
                                                       'type': 'Voice'}],
                                          'tag': {'class': 'APPLICATION',
                                                  'number': 12},
                                          'type': 'CHOICE'},
                    'Keywords-E-2-11': {'element': {'type': 'VisibleString'},
                                        'size': None,
                                        'type': 'SET OF'},
                    'Keywords2-E-2-11': {'element': {'type': 'VisibleString'},
                                         'size': None,
                                         'type': 'SET OF'},
                    'MaritalStatus-E-2-3-a': {'type': 'ENUMERATED',
                                              'values': {0: 'single',
                                                         1: 'married'}},
                    'MaritalStatus-E-2-3-b': {'type': 'ENUMERATED',
                                              'values': {0: 'single',
                                                         1: 'married',
                                                         2: '...',
                                                         3: 'widowed'}},
                    'MaritalStatus-E-2-3-c': {'type': 'ENUMERATED',
                                              'values': {0: 'single',
                                                         1: 'married',
                                                         2: '...',
                                                         3: 'widowed',
                                                         4: 'divorced'}},
                    'Months-E-4': {'type': 'ENUMERATED',
                                   'values': {1: 'january',
                                              2: 'february',
                                              3: 'march',
                                              4: 'april',
                                              5: 'may',
                                              6: 'june',
                                              7: 'july',
                                              8: 'august',
                                              9: 'september',
                                              10: 'october',
                                              11: 'november',
                                              12: 'december'}},
                    'Name-E-1-1': {'members': [{'name': 'givenName',
                                                'optional': False,
                                                'type': 'VisibleString'},
                                               {'name': 'initial',
                                                'optional': False,
                                                'type': 'VisibleString'},
                                               {'name': 'familyName',
                                                'optional': False,
                                                'type': 'VisibleString'}],
                                   'tag': {'class': 'APPLICATION',
                                           'number': 1},
                                   'type': 'SEQUENCE'},
                    'NamesOfMemberNations-E-2-10': {'element': {'type': 'VisibleString'},
                                                    'size': None,
                                                    'type': 'SEQUENCE OF'},
                    'NamesOfMemberNations2-E-2-10': {'element': {'type': 'VisibleString'},
                                                     'size': None,
                                                     'type': 'SEQUENCE OF'},
                    'NamesOfOfficers-E-2-10': {'members': [{'name': 'president',
                                                            'optional': False,
                                                            'type': 'VisibleString'},
                                                           {'name': 'vicePresident',
                                                            'optional': False,
                                                            'type': 'VisibleString'},
                                                           {'name': 'secretary',
                                                            'optional': False,
                                                            'type': 'VisibleString'}],
                                               'type': 'SEQUENCE'},
                    'PDU-E-4': {'members': [{'name': 'alpha',
                                             'optional': False,
                                             'type': 'INTEGER'},
                                            {'name': 'beta',
                                             'optional': True,
                                             'type': 'IA5String'},
                                            {'element': {'type': 'Parameter'},
                                             'name': 'gamma',
                                             'optional': False,
                                             'size': None,
                                             'type': 'SEQUENCE OF'},
                                            {'name': 'delta',
                                             'optional': False,
                                             'type': 'BOOLEAN'}],
                                'type': 'SET'},
                    'PackedBCDString-E-2-8': {'type': 'CHARACTER STRING'},
                    'ParameterList-E-4': {'element': {'type': 'Parameter'},
                                          'size': [(1, 63)],
                                          'type': 'SET OF'},
                    'PatientIdentifier-E-2-9': {'members': [{'name': 'name',
                                                             'optional': False,
                                                             'type': 'VisibleString'},
                                                            {'members': [{'name': 'room',
                                                                          'optional': False,
                                                                          'type': 'INTEGER'},
                                                                         {'name': 'outPatient',
                                                                          'optional': False,
                                                                          'type': 'NULL'}],
                                                             'name': 'roomNumber',
                                                             'optional': False,
                                                             'type': 'CHOICE'}],
                                                'type': 'SEQUENCE'},
                    'PersonalStatus-E-2-5': {'size': None,
                                             'type': 'BIT STRING'},
                    'PersonnelRecord-E-1-1': {'members': [{'name': 'name',
                                                           'optional': False,
                                                           'type': 'Name-E-1-1'},
                                                          {'name': 'title',
                                                           'optional': False,
                                                           'type': 'VisibleString'},
                                                          {'name': 'number',
                                                           'optional': False,
                                                           'type': 'EmployeeNumber-E-1-1'},
                                                          {'name': 'dateOfHire',
                                                           'optional': False,
                                                           'type': 'Date-E-1-1'},
                                                          {'name': 'nameOfSpouse',
                                                           'optional': False,
                                                           'type': 'Name-E-1-1'},
                                                          {'default': [],
                                                           'element': {'type': 'ChildInformation-E-1-1'},
                                                           'name': 'children',
                                                           'optional': False,
                                                           'size': None,
                                                           'type': 'SEQUENCE OF'}],
                                              'tag': {'class': 'APPLICATION',
                                                      'number': 0},
                                              'type': 'SET'},
                    'Record-E-2-10-a': {'members': [{'name': 'userName',
                                                     'optional': False,
                                                     'type': 'VisibleString'},
                                                    {'name': 'password',
                                                     'optional': False,
                                                     'type': 'VisibleString'},
                                                    {'name': 'accountNumber',
                                                     'optional': False,
                                                     'type': 'INTEGER'},
                                                    {'name': '...',
                                                     'optional': False,
                                                     'type': ''},
                                                    {'name': '...',
                                                     'optional': False,
                                                     'type': ''}],
                                        'type': 'SEQUENCE'},
                    'Record-E-2-10-b': {'members': [{'name': 'userName',
                                                     'optional': False,
                                                     'type': 'VisibleString'},
                                                    {'name': 'password',
                                                     'optional': False,
                                                     'type': 'VisibleString'},
                                                    {'name': 'accountNumber',
                                                     'optional': False,
                                                     'type': 'INTEGER'},
                                                    {'name': '...',
                                                     'optional': False,
                                                     'type': ''},
                                                    {'name': 'lastLoggedIn',
                                                     'optional': True,
                                                     'type': 'GeneralizedTime'},
                                                    {'name': 'minutesLastLoggedIn',
                                                     'optional': False,
                                                     'type': 'INTEGER'},
                                                    {'name': '...',
                                                     'optional': False,
                                                     'type': ''}],
                                        'type': 'SEQUENCE'},
                    'Record-E-2-10-c': {'members': [{'name': 'userName',
                                                     'optional': False,
                                                     'type': 'VisibleString'},
                                                    {'name': 'password',
                                                     'optional': False,
                                                     'type': 'VisibleString'},
                                                    {'name': 'accountNumber',
                                                     'optional': False,
                                                     'type': 'INTEGER'},
                                                    {'name': '...',
                                                     'optional': False,
                                                     'type': ''},
                                                    {'name': 'lastLoggedIn',
                                                     'optional': True,
                                                     'type': 'GeneralizedTime'},
                                                    {'name': 'minutesLastLoggedIn',
                                                     'optional': False,
                                                     'type': 'INTEGER'},
                                                    {'name': 'certificate',
                                                     'optional': False,
                                                     'type': 'Certificate'},
                                                    {'name': 'thumb',
                                                     'optional': True,
                                                     'type': 'ThumbPrint'},
                                                    {'name': '...',
                                                     'optional': False,
                                                     'type': ''}],
                                        'type': 'SEQUENCE'},
                    'Second-half-E-4': {'type': 'Months'},
                    'Second-quarter-E-4': {'type': 'Months'},
                    'SmallPrime-E-4-a': {'restricted-to': [2,
                                                           3,
                                                           5,
                                                           7,
                                                           11,
                                                           13,
                                                           17,
                                                           19,
                                                           23,
                                                           29],
                                         'type': 'INTEGER'},
                    'SmallPrime-E-4-b': {'restricted-to': [2, 3],
                                         'type': 'INTEGER'},
                    'SmallPrime-E-4-c': {'restricted-to': [2, 3, 5, 7, 11],
                                         'type': 'INTEGER'},
                    'SmallPrime-E-4-d': {'restricted-to': [2,
                                                           3,
                                                           5,
                                                           7,
                                                           11,
                                                           13,
                                                           17,
                                                           19],
                                         'type': 'INTEGER'},
                    'Surname-E-2-6': {'type': 'PrintableString'},
                    'T-14-10': {'members': [{'name': 'a',
                                             'optional': False,
                                             'type': 'BOOLEAN'},
                                            {'element': {'type': 'INTEGER'},
                                             'name': 'b',
                                             'optional': False,
                                             'size': None,
                                             'type': 'SET OF'}],
                                'type': 'SEQUENCE'},
                    'TestPDU-E-4': {'type': 'PDU'},
                    'Text-block-E-4': {'element': {'type': 'VisibleString'},
                                       'size': None,
                                       'type': 'SEQUENCE OF'},
                    'Third-quarter-E-4': {'type': 'Months'},
                    'UserName-E-2-11-a': {'members': [{'name': 'personalName',
                                                       'optional': False,
                                                       'tag': {'number': 0},
                                                       'type': 'VisibleString'},
                                                      {'name': 'organizationName',
                                                       'optional': False,
                                                       'tag': {'number': 1},
                                                       'type': 'VisibleString'},
                                                      {'name': 'countryName',
                                                       'optional': False,
                                                       'tag': {'number': 2},
                                                       'type': 'VisibleString'}],
                                          'type': 'SET'},
                    'UserName-E-2-11-b': {'members': [{'name': 'personalName',
                                                       'optional': False,
                                                       'tag': {'number': 0},
                                                       'type': 'VisibleString'},
                                                      {'name': 'organizationName',
                                                       'optional': True,
                                                       'tag': {'number': 1},
                                                       'type': 'VisibleString'},
                                                      {'name': 'countryName',
                                                       'optional': True,
                                                       'tag': {'number': 2},
                                                       'type': 'VisibleString'}],
                                          'type': 'SET'},
                    'UserName-E-2-11-c': {'members': [{'name': 'personalName',
                                                       'optional': False,
                                                       'type': 'VisibleString'},
                                                      {'name': 'organizationName',
                                                       'optional': True,
                                                       'type': 'VisibleString'},
                                                      {'name': 'countryName',
                                                       'optional': True,
                                                       'type': 'VisibleString'},
                                                      {'name': '...',
                                                       'optional': False,
                                                       'type': ''},
                                                      {'name': '...',
                                                       'optional': False,
                                                       'type': ''}],
                                          'type': 'SET'},
                    'UserName-E-2-11-d': {'members': [{'name': 'personalName',
                                                       'optional': False,
                                                       'type': 'VisibleString'},
                                                      {'name': 'organizationName',
                                                       'optional': True,
                                                       'type': 'VisibleString'},
                                                      {'name': 'countryName',
                                                       'optional': True,
                                                       'type': 'VisibleString'},
                                                      {'name': '...',
                                                       'optional': False,
                                                       'type': ''},
                                                      {'name': 'internetEmailAddress',
                                                       'optional': False,
                                                       'type': 'VisbleString'},
                                                      {'name': 'faxNumber',
                                                       'optional': True,
                                                       'type': 'VisibleString'},
                                                      {'name': '...',
                                                       'optional': False,
                                                       'type': ''}],
                                          'type': 'SET'},
                    'UserName-E-2-11-e': {'members': [{'name': 'personalName',
                                                       'optional': False,
                                                       'type': 'VisibleString'},
                                                      {'name': 'organizationName',
                                                       'optional': True,
                                                       'type': 'VisibleString'},
                                                      {'name': 'countryName',
                                                       'optional': True,
                                                       'type': 'VisibleString'},
                                                      {'name': '...',
                                                       'optional': False,
                                                       'type': ''},
                                                      {'name': 'internetEmailAddress',
                                                       'optional': False,
                                                       'type': 'VisbleString'},
                                                      {'name': 'faxNumber',
                                                       'optional': True,
                                                       'type': 'VisibleString'},
                                                      {'name': 'phoneNumber',
                                                       'optional': True,
                                                       'type': 'VisibleString'},
                                                      {'name': '...',
                                                       'optional': False,
                                                       'type': ''}],
                                          'type': 'SET'},
                    'V-E-4': {'type': 'Z'},
                    'Voice-E-2-13': {'members': [{'name': 'english',
                                                  'optional': False,
                                                  'size': None,
                                                  'type': 'OCTET STRING'},
                                                 {'name': 'swahili',
                                                  'optional': False,
                                                  'size': None,
                                                  'type': 'OCTET STRING'}],
                                     'type': 'CHOICE'},
                    'W-E-4': {'type': 'Z'},
                    'X-E-4': {'type': 'Z'},
                    'Y-E-4': {'type': 'Z'},
                    'Z-E-4': {'members': [{'name': 'a',
                                           'optional': False,
                                           'type': 'A'},
                                          {'name': 'b',
                                           'optional': False,
                                           'type': 'B'},
                                          {'name': 'c',
                                           'optional': False,
                                           'type': 'C'},
                                          {'name': 'd',
                                           'optional': False,
                                           'type': 'D'},
                                          {'name': 'e',
                                           'optional': False,
                                           'type': 'E'}],
                              'type': 'CHOICE'}},
          'values': {'acmeCorp-E-2-10': {'type': 'NamesOfOfficers-E-2-10',
                                         'value': ['{',
                                                   'president',
                                                   ['Jane Doe'],
                                                   'vicePresident',
                                                   ['John Doe'],
                                                   'secretary',
                                                   ['Joe Doe'],
                                                   '}']},
                     'badgeNumber-E-2-12': {'type': 'AcmeBadgeNumber-E-2-12',
                                            'value': ['2345']},
                     'balance-E-2-2': {'type': 'CheckingAccountBalance-E-2-2',
                                       'value': ['0']},
                     'billClinton-E-2-5': {'type': 'PersonalStatus-E-2-5',
                                           'value': ['married',
                                                     'employed',
                                                     'collegeGraduate']},
                     'body1-E-2-5': {'type': 'G3FacsimilePage-E-2-5',
                                     'value': ["'1101'B"]},
                     'body2-E-2-5': {'type': 'G3FacsimilePage-E-2-5',
                                     'value': ["'1101000'B"]},
                     'dayOfTheMonth-E-2-2-c': {'type': 'DayOfTheMonth-E-2-2',
                                               'value': ['4']},
                     'file-E-2-13': {'type': 'FileIdentifier-E-2-13-a',
                                     'value': ['serialNumber',
                                               ':',
                                               ['106448503']]},
                     'fileId1-E-2-13-a': {'type': 'FileIdentifier-E-2-13-c',
                                          'value': ['relativeName',
                                                    ':',
                                                    ['MarchProgressReport.doc']]},
                     'fileId1-E-2-13-b': {'type': 'FileIdentifier-E-2-13-d',
                                          'value': ['relativeName',
                                                    ':',
                                                    ['MarchProgressReport.doc']]},
                     'fileId2-E-2-13-a': {'type': 'FileIdentifier-E-2-13-c',
                                          'value': ['serialNumber',
                                                    ':',
                                                    ['214']]},
                     'fileId2-E-2-13-b': {'type': 'FileIdentifier-E-2-13-d',
                                          'value': ['serialNumber',
                                                    ':',
                                                    ['214']]},
                     'fileId3-E-2-13-c': {'type': 'FileIdentifier-E-2-13-d',
                                          'value': ['unidentified',
                                                    ':',
                                                    ['NULL']]},
                     'firstDay-E-2-3': {'type': 'DayOfTheWeek-E-2-3',
                                        'value': ['sunday']},
                     'firstTwo-E-2-10': {'type': 'NamesOfMemberNations-E-2-10',
                                         'value': ['{',
                                                   'Australia',
                                                   'Austria',
                                                   '}']},
                     'firstTwo2-E-2-10': {'type': 'NamesOfMemberNations2-E-2-10',
                                          'value': ['{',
                                                    'memberNation',
                                                    ['Australia'],
                                                    'memberNation',
                                                    ['Austria'],
                                                    '}']},
                     'girth-E-2-4': {'type': 'App-X-Real-E-2-4',
                                     'value': ['{',
                                               'mantissa',
                                               ['16'],
                                               'base',
                                               ['2'],
                                               'exponent',
                                               ['1'],
                                               '}']},
                     'greekCapitalLetterSigma-E-2-7': {'type': 'BMPString',
                                                       'value': ['{',
                                                                 '0',
                                                                 ',',
                                                                 '0',
                                                                 ',',
                                                                 '3',
                                                                 ',',
                                                                 '163',
                                                                 '}']},
                     'hillaryClinton-E-2-5': {'type': 'PersonalStatus-E-2-5',
                                              'value': ["'110100'B"]},
                     'image-E-2-5': {'type': 'G3FacsimilePage-E-2-5',
                                     'value': ["'100110100100001110110'B"]},
                     'image-E-2-6': {'type': 'G4FacsimilePage-E-2-6',
                                     'value': ["'3FE2EBAD471005'H"]},
                     'infinity-E-2-7': {'type': 'UTF8String',
                                        'value': ['{',
                                                  '0',
                                                  ',',
                                                  '0',
                                                  ',',
                                                  '34',
                                                  ',',
                                                  '30',
                                                  '}']},
                     'lastPatient-E-2-9': {'type': 'PatientIdentifier-E-2-9',
                                           'value': ['{',
                                                     'name',
                                                     ['Jane Doe'],
                                                     'roomNumber',
                                                     ['outPatient',
                                                      ':',
                                                      ['NULL']],
                                                     '}']},
                     'map1-E-2-5': {'type': 'BitField-E-2-5',
                                    'value': ["'100110100100'B"]},
                     'map2-E-2-5': {'type': 'BitField-E-2-5',
                                    'value': ["'9A4'H"]},
                     'myGreeting-E-2-13': {'type': 'Greeting-E-2-13-c',
                                           'value': ['recording',
                                                     ':',
                                                     ['english',
                                                      ':',
                                                      ["'019838547E0'H"]]]},
                     'pi-E-2-4-a': {'type': 'REAL',
                                    'value': ['{',
                                              'mantissa',
                                              ['3141592653589793238462643383279'],
                                              'base',
                                              ['10'],
                                              'exponent',
                                              ['-30'],
                                              '}']},
                     'pi-E-2-4-b': {'type': 'REAL',
                                    'value': ['3.14159265358979323846264338327']},
                     'president-E-2-6': {'type': 'Surname-E-2-6',
                                         'value': ['Clinton']},
                     'property-E-2-7': {'type': 'UTF8String',
                                        'value': ['{',
                                                  'f ',
                                                  'rightwardsArrow-E-2-7',
                                                  ' ',
                                                  'infinity-E-2-7',
                                                  '}']},
                     'rightwardsArrow-E-2-7': {'type': 'UTF8String',
                                               'value': ['{',
                                                         '0',
                                                         ',',
                                                         '0',
                                                         ',',
                                                         '33',
                                                         ',',
                                                         '146',
                                                         '}']},
                     'someASN1Keywords-E-2-11': {'type': 'Keywords-E-2-11',
                                                 'value': ['{',
                                                           'INTEGER',
                                                           'BOOLEAN',
                                                           'REAL',
                                                           '}']},
                     'someASN1Keywords2-E-2-11': {'type': 'Keywords2-E-2-11',
                                                  'value': ['{',
                                                            'keyword',
                                                            ['INTEGER'],
                                                            'keyword',
                                                            ['BOOLEAN'],
                                                            'keyword',
                                                            ['REAL'],
                                                            '}']},
                     'sunnyDaysLastWeek1-E-2-5': {'type': 'DaysOfTheWeek-E-2-5',
                                                  'value': ['sunday',
                                                            'monday',
                                                            'wednesday']},
                     'sunnyDaysLastWeek2-E-2-5': {'type': 'DaysOfTheWeek-E-2-5',
                                                  'value': ["'1101'B"]},
                     'sunnyDaysLastWeek3-E-2-5': {'type': 'DaysOfTheWeek-E-2-5',
                                                  'value': ["'1101000'B"]},
                     'today-E-2-2': {'type': 'DayOfTheMonth-E-2-2',
                                     'value': ['first']},
                     'trailer-E-2-5': {'type': 'BIT STRING',
                                       'value': '0x0123456789ABCDEF'},
                     'unknown-E-2-2': {'type': 'DayOfTheMonth-E-2-2',
                                       'value': ['0']},
                     'user-E-2-11-a': {'type': 'UserName-E-2-11-a',
                                       'value': ['{',
                                                 'countryName',
                                                 ['Nigeria'],
                                                 'personalName',
                                                 ['Jonas Maruba'],
                                                 'organizationName',
                                                 ['Meteorology, Ltd.'],
                                                 '}']},
                     'user-E-2-11-b': {'type': 'UserName-E-2-11-c',
                                       'value': ['{',
                                                 'personalName',
                                                 ['Jonas Maruba'],
                                                 '}']},
                     'user-E-2-11-c': {'type': 'UserName-E-2-11-d',
                                       'value': ['{',
                                                 'personalName',
                                                 ['Jonas Maruba'],
                                                 'internetEmailAddress',
                                                 ['jonas@meteor.ngo.com'],
                                                 '}']},
                     'user-E-2-11-d': {'type': 'UserName-E-2-11-e',
                                       'value': ['{',
                                                 'personalName',
                                                 ['Jonas Maruba'],
                                                 'internetEmailAddress',
                                                 ['jonas@meteor.ngo.com'],
                                                 '}']}}}}
