name: Python package

on: [push, pull_request]

jobs:

  test-python:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coveralls
    - name: Test
      run: |
        coverage run --source=asn1tools setup.py test
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop

  test-python-sdist:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: |
        make test-sdist

  test-c:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install -qq valgrind -y
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: |
        make test-c
        make -C examples/benchmarks/c_source
        (cd tests && bash <(curl -s https://codecov.io/bash) -X coveragepy)

  examples:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: |
        (cd examples/benchmarks/packages && wget https://github.com/ANSSI-FR/pycrate/archive/master.zip && unzip -qq master.zip)
        env PYTHONPATH=.:examples/benchmarks/packages/pycrate-master python examples/benchmarks/packages/ber.py
        env PYTHONPATH=.:examples/benchmarks/packages/pycrate-master python examples/benchmarks/packages/uper.py
        env PYTHONPATH=. python examples/benchmarks/codecs.py
        env PYTHONPATH=. python examples/benchmarks/question/question.py
        env PYTHONPATH=. python examples/hello_world.py
        env PYTHONPATH=. python examples/x509_pem.py
        env PYTHONPATH=. python examples/compact_extensions_uper/main.py
        env PYTHONPATH=. python examples/programming_types/main.py

  release:
    needs: [test-python, test-python-sdist, test-c, examples]
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pypa/build
      run: |
        python -m pip install build --user
    - name: Build a binary wheel and a source tarball
      run: |
        git clean -dfx
        python -m build --sdist --outdir dist/ .
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        skip_existing: true
        password: ${{ secrets.pypi_password }}
